name: JavaScript/TypeScript Linter
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/frontend/**.js'
      - 'src/frontend/**.jsx'
      - 'src/frontend/**.ts'
      - 'src/frontend/**.tsx'
  pull_request:
    paths:
      - 'src/frontend/**.js'
      - 'src/frontend/**.jsx'
      - 'src/frontend/**.ts'
      - 'src/frontend/**.tsx'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: src/frontend
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json
      
      - name: Install Dependencies
        run: npm ci || npm install
      
      - name: Run ESLint
        id: eslint
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep -E '^src/frontend/.*\.(js|jsx|ts|tsx)$' || true)
            if [ ! -z "$FILES" ]; then
              echo "Linting changed files: $FILES"
              npx eslint ${FILES#src/frontend/} --format json --output-file eslint_report.json --max-warnings=0 || echo "ESLINT_FAILED=true" >> $GITHUB_ENV
            else
              echo "No JavaScript/TypeScript files changed in frontend"
              echo '[]' > eslint_report.json
            fi
          else
            echo "Linting all JavaScript/TypeScript files in frontend"
            npx eslint . --ext .js,.jsx,.ts,.tsx --format json --output-file eslint_report.json --max-warnings=0 || echo "ESLINT_FAILED=true" >> $GITHUB_ENV
          fi
      
      - name: Annotate Code Linting Results
        if: always()
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "src/frontend/eslint_report.json"
      
      - name: Check Linting Results
        if: env.ESLINT_FAILED == 'true'
        run: exit 1