name: JavaScript/TypeScript Linter
on:
  push:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'
  pull_request:
    paths:
      - '**.js'
      - '**.jsx'
      - '**.ts'
      - '**.tsx'

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      # Remove npm cache action since we're handling package installation differently
      
      - name: Install Dependencies
        run: |
          # Initialize npm if package.json doesn't exist
          if [ ! -f package.json ]; then
            npm init -y
          fi
          
          # Install ESLint and related packages
          npm install --save-dev eslint @eslint/js @typescript-eslint/parser @typescript-eslint/eslint-plugin typescript
          
          # Create ESLint config if it doesn't exist
          if [ ! -f .eslintrc.json ]; then
            echo '{
              "extends": [
                "eslint:recommended",
                "plugin:@typescript-eslint/recommended"
              ],
              "parser": "@typescript-eslint/parser",
              "plugins": ["@typescript-eslint"],
              "env": {
                "node": true,
                "browser": true,
                "es2021": true
              },
              "parserOptions": {
                "ecmaVersion": "latest",
                "sourceType": "module"
              },
              "rules": {
                "no-unused-vars": "warn",
                "no-console": "warn"
              }
            }' > .eslintrc.json
          fi
      
      - name: Run ESLint
        id: eslint
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            # For pull requests, only lint changed files
            FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD | grep -E '\.(js|jsx|ts|tsx)$' || true)
            if [ ! -z "$FILES" ]; then
              echo "Linting changed files: $FILES"
              npx eslint $FILES --format json --output-file eslint_report.json --max-warnings=0 || echo "ESLINT_FAILED=true" >> $GITHUB_ENV
            else
              echo "No JavaScript/TypeScript files changed"
              echo '[]' > eslint_report.json
            fi
          else
            # On direct pushes, lint all files
            echo "Linting all JavaScript/TypeScript files"
            npx eslint . --ext .js,.jsx,.ts,.tsx --format json --output-file eslint_report.json --max-warnings=0 || echo "ESLINT_FAILED=true" >> $GITHUB_ENV
          fi
      
      - name: Annotate Code Linting Results
        if: always()
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
      
      - name: Check Linting Results
        if: env.ESLINT_FAILED == 'true'
        run: exit 1